### ISSUE TITLE
[Feature Request] Option to send PcVolumeControl to systray

### ISSUE THREAD

**Issue by karasuhebi** [Wavesonics/PcVolumeControlWindows#1]
It would be nice to be able to send the app into the systray so it's not taking up a lot of space on the taskbar. Maybe have a "Start with Windows" option as well?

**Comment by Wavesonics** [comment]
Absolutely! On my list of things to do, and now that both client and server are pretty stable it's probably the next thing I'll implement. Thanks for the feed back!

**Comment by karasuhebi** [comment]
Cool! Glad to hear it, thanks for the fast reply. Will the PC app ping me when there's an update or will I have to keep checking back?

**Comment by Wavesonics** [comment]
Ya right now you will have to check. I will build some sort of auto-check functionality in the future.

**Comment by Wavesonics** [comment]
v7 Windows app now runs in the tray. It also will notify the user of new releases.

**Comment by karasuhebi** [comment]
Nice! Thanks for this :D

**Comment by karasuhebi** [comment]
Just tested it and it worked like a charm! Here's some feedback though:

It would be nice if we could get an option in the UI so we can choose if we want it to go to the systray or keep the old behavior where it would just close. Adding to that point, it would be nice to have the choice between having it minimize to the systray or close to the systray. 

It would also be nice if when you click on the X to close it, it would tell you via a balloon tip (or notification via the Action Center now in Windows 10 I guess) that it went to the systray instead of actually closing. Just so users are aware.

I also tested the Start on Boot option and this also worked flawlessly (although I think Remove on Boot should be called Remove Start on Boot...or just remove the buttons and make it a checkmark for an even clearer aesthetic). Now that this is a thing though, I think we should get an option to make it where PcVolumeControl starts minimized as well.
 
As far as the option to check for updates, is there a way to make it so the link only shows up when there actually is an update? Or make it so the link just checks to see if there's an update instead of automatically taking us to the GitHub when there's no new release?
