### ISSUE TITLE
Automatic shut down

### ISSUE THREAD

**Issue by Psychocrysma** [Wavesonics/PcVolumeControlWindows#4]
Thrice before, I have noticed, just when I'm about to make use of the app, that the server has died (the process is completely gone) for seemingly no reason. My machine runs many other servers so it runs in permanence. Not sure what the issue could be exactly. Is it a scheduled exit (because of a thread ending or something?) or a crash? Not sure. I don't mind giving more info if you need them.

**Comment by Wavesonics** [comment]
I have noticed this as well! I will have to look into it soon. Thanks for the report!

**Comment by Wavesonics** [comment]
I found the bug, will be releasing an update soon.

**Comment by Wavesonics** [comment]
Fixed in v8 release
